#!/usr/bin/env python3

    # Add prefix string to all files in a folder

import sys, os, argparse, subprocess
from os import path

parser = argparse.ArgumentParser(description="Add or remove prefix to filenames")

parser.add_argument("pre", help="prefix string to be appended before files")
parser.add_argument("-r", "--remove", help="remove prefix from files instead", action="store_true")

args = parser.parse_args()

currentDir = os.getcwd()  # Get where script was executed
pre = args.pre


for file in os.listdir(currentDir):
    if args.remove is True:  # Remove prefix
        if file.startswith(pre) is False:
            continue
        
    else:  # Add prefix
        newFile = path.join(currentDir, pre + file)
        file = path.join(currentDir, file)  # Turn file name into absolute path
        os.rename(file, newFile)
        print ("Adding prefix to file {}".format(file))
