#!/usr/bin/env python3

# Add prefix string to all files in a folder

import os
import argparse
from os import path

parser = argparse.ArgumentParser(description="Add or remove prefix to filenames")

parser.add_argument("pre", help="prefix string to be appended before files")
parser.add_argument("-r", "--remove", help="remove prefix from files instead", action="store_true")
parser.add_argument("-v", "--vervose", help="print lines to indicate what is happening", action="store_true")

args = parser.parse_args()

currentDir = os.getcwd()  # Get where script was executed
pre = args.pre
vervose = args.vervose


for file in os.listdir(currentDir):
    if args.remove is True:  # Remove prefix
        if file.startswith(pre) is False:
            continue
        else:
            newFile = path.join(currentDir, file[len(pre):])
            file = path.join(currentDir, file)
            os.rename(file, newFile)
            if vervose is True:
                print ("Removing prefix from file {}".format(file))
    else:  # Add prefix
        newFile = path.join(currentDir, pre + file)
        file = path.join(currentDir, file)  # Turn file name into absolute path
        os.rename(file, newFile)
        if vervose is True:
            print ("Adding prefix to file {}".format(file))
